name: vidastech
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85774
title: 'Share our creative works & event'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0B0C0E'
    - '#F2F2F1'
    - '#5B706D'
    - '#91A39A'
    - '#BCC5BD'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
